
/* File generated by gen_cfile.py. Should not be modified. */

#include "TestSlave.h"

UNS8 Read_Inputs_8_Bit[8] = {0};
UNS8 Write_Outputs_8_Bit[8] = {0};



/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/


#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TestSlave_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TestSlave_bDeviceNodeId = 0x01;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TestSlave_iam_a_slave = 1;

TIMER_HANDLE TestSlave_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TestSlave_obj1000 = 0x0;	/* 0 */
                    subindex TestSlave_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TestSlave_obj1001 = 0x0;	/* 0 */
                    subindex TestSlave_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TestSlave_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t TestSlave_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 TestSlave_obj1005 = 0x0;   

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 TestSlave_obj1006 = 0x0;   

/* index 0x100C :   Guard Time */ 
                    UNS16 TestSlave_obj100C = 0x0;   

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TestSlave_obj100D = 0x0;   

/* index 0x1014 :   Emergency COB ID */
                    UNS32 TestSlave_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 TestSlave_highestSubIndex_obj1016 = 0;
                    UNS32 TestSlave_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 TestSlave_obj1017 = 0x3E8;	/* 1000 */
                    ODCallback_t TestSlave_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex TestSlave_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 TestSlave_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 TestSlave_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 TestSlave_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 TestSlave_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex TestSlave_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x601;	
                    UNS32 TestSlave_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x581;	
                    subindex TestSlave_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&TestSlave_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. 接收主站RPDO1 */
                    UNS8 TestSlave_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1400_COB_ID_used_by_PDO = 0x201;	/* 512 */
                    UNS8 TestSlave_obj1400_Transmission_Type = 0xFF;	/* 异步接收 */
                    UNS16 TestSlave_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. 接收主站RPDO2 */
                    UNS8 TestSlave_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1401_COB_ID_used_by_PDO = 0x301;	
                    UNS8 TestSlave_obj1401_Transmission_Type = 0xFF;	
                    UNS16 TestSlave_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 TestSlave_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 TestSlave_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex TestSlave_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1600 = 3; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1600[] = 
                    {
                      0x60400010, // 6040h sub0, 16 bit
                      0x60600008, // 6060h sub0, 8 bit
                      0x607A0020  // 607Ah sub0, 32 bit
                    };
                    subindex TestSlave_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1600[2] },
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1601 = 2; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1601[] = 
                    {
                      0x60FF0020, // 60FFh:00, 32 bit
                      0x60710010  // 6071h:00, 16 bit
                    };
                    subindex TestSlave_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1601[1] },
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TestSlave_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1602[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1602[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1602[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1602[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1602[7] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TestSlave_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1603[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1603[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1603[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1603[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1800_COB_ID_used_by_PDO = 0x181;	
                    UNS8 TestSlave_obj1800_Transmission_Type = 0xFF;	/* 异步/事件触发 */
                    UNS16 TestSlave_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1800_Event_Timer = 0;	// ms周期发送TPDO1
                    UNS8 TestSlave_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL
                     };
                    subindex TestSlave_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1801_COB_ID_used_by_PDO = 0x281;	/* 640 */
                    UNS8 TestSlave_obj1801_Transmission_Type = 0xFF;	/* 0 */
                    UNS16 TestSlave_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1801_Event_Timer = 0;	
                    UNS8 TestSlave_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 TestSlave_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 TestSlave_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 TestSlave_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TestSlave_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 TestSlave_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t TestSlave_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex TestSlave_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A00[] = 
                    {
                      0x60410010,  // 6041:00, 16位 状态字
                      0x606C0020  // 606C:00, 32位 实际速度
                    };
                    subindex TestSlave_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A00[1] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A01 = 2; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A01[] = 
                    {
                      0x60640020,   // 6064:00, 32位 实际位置
                      0x60770010   // 6077:00, 16位 实际力矩
                    };
                    subindex TestSlave_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A01[1] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A02 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A02[] = 
                    {
                      0x0	
                    };
                    subindex TestSlave_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A02[0] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 TestSlave_highestSubIndex_obj1A03 = 1; /* number of subindex - 1*/
                    UNS32 TestSlave_obj1A03[] = 
                    {
                      0x0
                    };
                    subindex TestSlave_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj1A03[0] }
                     };

/* index 0x6000 :   Mapped variable Read Inputs 8 Bit */
                    UNS8 TestSlave_highestSubIndex_obj6000 = 8; /* number of subindex - 1*/
                    subindex TestSlave_Index6000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj6000 },
                       { RO, uint8, sizeof (UNS8), (void*)&Read_Inputs_8_Bit[0] },
                       { RO, uint8, sizeof (UNS8), (void*)&Read_Inputs_8_Bit[1] },
                       { RO, uint8, sizeof (UNS8), (void*)&Read_Inputs_8_Bit[2] },
                       { RO, uint8, sizeof (UNS8), (void*)&Read_Inputs_8_Bit[3] },
                       { RO, uint8, sizeof (UNS8), (void*)&Read_Inputs_8_Bit[4] },
                       { RO, uint8, sizeof (UNS8), (void*)&Read_Inputs_8_Bit[5] },
                       { RO, uint8, sizeof (UNS8), (void*)&Read_Inputs_8_Bit[6] },
                       { RO, uint8, sizeof (UNS8), (void*)&Read_Inputs_8_Bit[7] }
                     };

/* index 0x6200 :   Mapped variable Write Outputs 8 Bit */
                    UNS8 TestSlave_highestSubIndex_obj6200 = 8; /* number of subindex - 1*/
                    subindex TestSlave_Index6200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj6200 },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[1] },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[2] },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[3] },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[4] },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[5] },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[6] },
                       { RW, uint8, sizeof (UNS8), (void*)&Write_Outputs_8_Bit[7] }
                     };

/* index 0x6040 :   Controlword */
                    UNS16 TestSlave_obj6040 = 0x0;  /* 初始值 */
                    ODCallback_t TestSlave_Index6040_callbacks[] = { NULL };
                    subindex TestSlave_Index6040[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj6040 }
                     };
                    

/*
Bit 0	 Ready to Switch On	1: 准备好开机
Bit 1	 Switched On		1: 已开机
Bit 2	 Operation Enabled	1: 允许运行
Bit 3	 Fault	1: 故障状态
Bit 4	 Voltage Enabled 1: 母线电压正常
Bit 5	 Quick Stop			0: 正在急停  1: 正常
Bit 6	 Switch On Disabled 1: 禁止开机
Bit 9 (Remote) 正常 1: 表示远程控制
Bit 10: Target Reached (到达位置/速度为0)
Bit 12: Setpoint Acknowledge (收到新目标)
*/

/* index 0x6041 :   Statusword 状态字，反映驱动器当前状态 */
                    UNS16 TestSlave_obj6041 = 0x0;  
                    subindex TestSlave_Index6041[] = 
                     {
                       { RO, uint16, sizeof (UNS16), (void*)&TestSlave_obj6041 }
                     };

/* index 0x605A :   Quick stop option code 急停停机策略 */
                    INTEGER16 TestSlave_obj605A = 2;
                    subindex TestSlave_Index605A[] =
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&TestSlave_obj605A }
                     };

/* index 0x605B :   Shutdown option code shutdown 停机策略 */
                    INTEGER16 TestSlave_obj605B = 0;
                    subindex TestSlave_Index605B[] =
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&TestSlave_obj605B }
                     };

/* index 0x605C :   Disable operation option code 去使能停机策略 */
                    INTEGER16 TestSlave_obj605C = 1;
                    subindex TestSlave_Index605C[] =
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&TestSlave_obj605C }
                     };

/* index 0x605D :   Halt option code 暂停停机策略 */
                    INTEGER16 TestSlave_obj605D = 1;
                    subindex TestSlave_Index605D[] =
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&TestSlave_obj605D }
                     };

/* index 0x605E :   Fault reaction option code 故障反应停机策略 */
                    INTEGER16 TestSlave_obj605E = 2;
                    subindex TestSlave_Index605E[] =
                     {
                       { RW, int16, sizeof (INTEGER16), (void*)&TestSlave_obj605E }
                     };

/* index 0x6060 :   Modes of operation 工作模式，用于设置驱动器的工作模式 */
// 1 - Profile Position Mode（轮廓位置模式） 
// 3 - Profile Velocity Mode（轮廓速度模式）
// 4 - Profile Torque Mode（轮廓转矩模式）
// 6 - Homing Mode（回零模式）
                    INTEGER8 TestSlave_obj6060 = 0x0;
                    ODCallback_t TestSlave_Index6060_callbacks[] = { NULL };
                    subindex TestSlave_Index6060[] = 
                     {
                       { RW, int8, sizeof (INTEGER8), (void*)&TestSlave_obj6060 }
                     };

/* index 0x6061 :   Modes of operation display 工作模式显示，反映驱动器当前的工作模式 */
                    INTEGER8 TestSlave_obj6061 = 0x0;
                    subindex TestSlave_Index6061[] = 
                    {
                      { RO, int8, sizeof (INTEGER8), (void*)&TestSlave_obj6061 }
                    };

/* index 0x607A :   Target position 目标位置，用于设置驱动器的目标位置 */
                    INTEGER32 TestSlave_obj607A = 0x0;
                    ODCallback_t TestSlave_Index607A_callbacks[] = { NULL };
                    subindex TestSlave_Index607A[] = 
                    {
                      { RW, int32, sizeof (INTEGER32), (void*)&TestSlave_obj607A }
                    };

/* index 0x60FF :   Target velocity 目标速度 */
                    INTEGER32 TestSlave_obj60FF = 0x0;
                    ODCallback_t TestSlave_Index60FF_callbacks[] = { NULL };
                    subindex TestSlave_Index60FF[] =  
                    {
                      { RW, int32, sizeof (INTEGER32), (void*)&TestSlave_obj60FF }
                    };

/* index 0x6064 :   Actual position 编码器读取的真实位置 */
                    INTEGER32 TestSlave_obj6064 = 0x0;
                    subindex TestSlave_Index6064[] = 
                    {
                      { RO, int32, sizeof (INTEGER32), (void*)&TestSlave_obj6064 }
                    };

/* index 0x606C :   Actual velocity 实际速度，反映驱动器当前的速度 */
                    INTEGER32 TestSlave_obj606C = 0x0;
                    subindex TestSlave_Index606C[] = 
                    {
                      { RO, int32, sizeof (INTEGER32), (void*)&TestSlave_obj606C }
                    };

/* index 0x6062 :   Position demand value */  // 位置环内部计算后的需求位置
                    INTEGER32 TestSlave_obj6062 = 0x0;
                    subindex TestSlave_Index6062[] = 
                    {
                      { RO, int32, sizeof (INTEGER32), (void*)&TestSlave_obj6062 }
                    };

/* index 0x6071 :   Target torque 目标力矩 */
                    INTEGER16 TestSlave_obj6071 = 0x0;
                    ODCallback_t TestSlave_Index6071_callbacks[] = { NULL };
                    subindex TestSlave_Index6071[] = 
                    {
                      { RW, int16, sizeof (INTEGER16), (void*)&TestSlave_obj6071 }
                    };

/* index 0x6077 :   Torque Actual Value 实际力矩 */
                    INTEGER16 TestSlave_obj6077 = 0x0;
                    subindex TestSlave_Index6077[] = 
                    {
                      { RO, int16, sizeof (INTEGER16), (void*)&TestSlave_obj6077 }
                    };

/* 0x6087 Torque slope 力矩斜坡 */
                    UNS32 TestSlave_obj6087 = 0;
                    subindex TestSlave_Index6087[] =
                    {
                        { RW, uint32, sizeof(UNS32), (void*)&TestSlave_obj6087 }
                    };

/* index 0x6083 :   Profile acceleration 加速度，用于设置驱动器的加速度参数 */
                    UNS32 TestSlave_obj6083 = 10000;  
                    subindex TestSlave_Index6083[] = 
                    {
                      { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj6083 }
                    };

/* index 0x6084 :   Profile deceleration 减速度，用于设置驱动器的减速度参数 */
                    UNS32 TestSlave_obj6084 = 10000;  
                    subindex TestSlave_Index6084[] = 
                    {
                      { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj6084 }
                    };

/* index 0x60C0 :   Interpolation time period */  // 插补时间周期，用于设置驱动器插补运算的时间周期
                    UNS8 TestSlave_obj60C0 = 0x0; 
                    subindex TestSlave_Index60C0[] = 
                    {
                      { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj60C0 }
                    };

/* index 0x60C1 :   Interpolation time index 插补时间索引，用于设置驱动器插补运算的时间索引 */
                    UNS8 TestSlave_obj60C1 = 0x0; 
                    subindex TestSlave_Index60C1[] = 
                    {
                      { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj60C1 }
                    };

/* index 0x6065 :   Following error window 跟随误差窗口，用于设置驱动器允许的最大跟随误差，即实际位置”与目标位置之间允许的最大偏差值 */
                    UNS32 TestSlave_obj6065 = 0x7FFFFFFF;  
                    subindex TestSlave_Index6065[] = 
                    {
                      { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj6065 }
                    };

/* index 0x6066 :   Following error timeout 跟随误差超时，定义了跟随误差超出窗口后，允许持续的最长时间 */
                    UNS16 TestSlave_obj6066 = 1000;  
                    subindex TestSlave_Index6066[] = 
                    {
                      { RW, uint16, sizeof (UNS16), (void*)&TestSlave_obj6066 }
                    };

/* index 0x607D :   Software position limit 软件位置限位，用于设置驱动器的最小和最大位置限位 */
                    UNS8 TestSlave_highestSubIndex_obj607D = 2;
                    INTEGER32 TestSlave_obj607D_min = 0x0;
                    INTEGER32 TestSlave_obj607D_max = 0x7FFFFFFF;
                    subindex TestSlave_Index607D[] = 
                    {
                      { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj607D },
                      { RW, int32, sizeof (INTEGER32), (void*)&TestSlave_obj607D_min },
                      { RW, int32, sizeof (INTEGER32), (void*)&TestSlave_obj607D_max }
                    };

/* index 0x607E :   Polarity 极性，用于设置驱动器的运动方向（转向） */
                    UNS8 TestSlave_obj607E = 0x0;  // 0：正方向，1：负方向
                    subindex TestSlave_Index607E[] = 
                    {
                      { RW, uint8, sizeof (UNS8), (void*)&TestSlave_obj607E }
                    };

/* index 0x6080 :   Max motor speed 最大电机速度，用于设置驱动器允许的最大速度 */
                    UNS32 TestSlave_obj6080 = 6000;  
                    subindex TestSlave_Index6080[] = 
                    {
                      { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj6080 }
                    };

/* index 0x6081 :   Profile velocity 轮廓速度设定值，即位置模式下的最大速度 */
                    UNS32 TestSlave_obj6081 = 3000;  
                    ODCallback_t TestSlave_Index6081_callbacks[] = { NULL };
                    subindex TestSlave_Index6081[] = 
                    {
                      { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj6081 }
                    };

/* index 0x6098 :   Homing method 回零方式，用于设置驱动器的回零方式 */
                    INTEGER8 TestSlave_obj6098 = 0x0;
                    ODCallback_t TestSlave_Index6098_callbacks[] = { NULL };
                    subindex TestSlave_Index6098[] =  
                    {
                      { RW, int8, sizeof (INTEGER8), (void*)&TestSlave_obj6098 }
                    };

/* index 0x6099 :   Homing speeds 回零速度，用于设置驱动器的回零速度参数 */
                    UNS8 TestSlave_highestSubIndex_obj6099 = 2;
                    UNS32 TestSlave_obj6099_speed1 = 0x0;  // 高速接近回零点
                    UNS32 TestSlave_obj6099_speed2 = 0x0;  // 精确定位
                    subindex TestSlave_Index6099[] = 
                    {
                      { RO, uint8, sizeof (UNS8), (void*)&TestSlave_highestSubIndex_obj6099 },
                      { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj6099_speed1 },
                      { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj6099_speed2 }
                    }; 

/* index 0x609A :   Homing acceleration 回零加速度，用于设置驱动器的回零加速度参数 */
                    UNS32 TestSlave_obj609A = 0x0;  
                    subindex TestSlave_Index609A[] = 
                    {
                      { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj609A }
                    };

/* 0x6085 Quick stop deceleration 急停减速度 */
                    UNS32 TestSlave_obj6085 = 20000;
                    subindex TestSlave_Index6085[] =
                    {
                        { RW, uint32, sizeof(UNS32), (void*)&TestSlave_obj6085 }
                    };

/* 0x6073 Max current 最大电流 */
                    UNS16 TestSlave_obj6073 = 0;
                    subindex TestSlave_Index6073[] =
                    {
                        { RW, uint16, sizeof(UNS16), (void*)&TestSlave_obj6073 }
                    };

/* 0x6072 Max torque 最大转矩 */
                    UNS16 TestSlave_obj6072 = 0;
                    subindex TestSlave_Index6072[] =
                    {
                        { RW, uint16, sizeof(UNS16), (void*)&TestSlave_obj6072 }
                    };



/* 0x60E0 Positive torque limit value 正方向最大转矩 */
                    INTEGER16 TestSlave_obj60E0 = 0;
                    subindex TestSlave_Index60E0[] =
                    {
                        { RW, int16, sizeof(INTEGER16), (void*)&TestSlave_obj60E0 }
                    };

/* 0x60E1 Negative torque limit value 负方向最大转矩 */
                    INTEGER16 TestSlave_obj60E1 = 0;
                    subindex TestSlave_Index60E1[] =
                    {
                        { RW, int16, sizeof(INTEGER16), (void*)&TestSlave_obj60E1 }
                    };

/* 0x6074 Torque demand value 内部转矩需求值反馈 */
// 内部计算出来、准备送入控制的转矩需求值
                    INTEGER16 TestSlave_obj6074 = 0;
                    subindex TestSlave_Index6074[] =
                    {
                        { RO, int16, sizeof(INTEGER16), (void*)&TestSlave_obj6074 }
                    };

/* index 0x607F :   Max Profile Velocity 最大轮廓速度 */
                    UNS32 TestSlave_obj607F = 5000;  // 初始值示例：3000（单位取决于配置，通常是 rpm 或 inc/s）
                    subindex TestSlave_Index607F[] = 
                    {
                      { RW, uint32, sizeof (UNS32), (void*)&TestSlave_obj607F }
                    };

/* 0x606B Velocity demand value 内部速度需求值反馈 */
// 内部计算出来、准备送入控制的速度需求值
                  INTEGER32 TestSlave_obj606B = 0;
                  subindex TestSlave_Index606B[] =
                  {
                      { RO, int32, sizeof(INTEGER32), (void*)&TestSlave_obj606B }
                  };




/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TestSlave_objdict[] = 
{
  { (subindex*)TestSlave_Index1000,sizeof(TestSlave_Index1000)/sizeof(TestSlave_Index1000[0]), 0x1000},
  { (subindex*)TestSlave_Index1001,sizeof(TestSlave_Index1001)/sizeof(TestSlave_Index1001[0]), 0x1001},
  { (subindex*)TestSlave_Index1017,sizeof(TestSlave_Index1017)/sizeof(TestSlave_Index1017[0]), 0x1017},
  { (subindex*)TestSlave_Index1018,sizeof(TestSlave_Index1018)/sizeof(TestSlave_Index1018[0]), 0x1018},
  { (subindex*)TestSlave_Index1200,sizeof(TestSlave_Index1200)/sizeof(TestSlave_Index1200[0]), 0x1200},
  { (subindex*)TestSlave_Index1400,sizeof(TestSlave_Index1400)/sizeof(TestSlave_Index1400[0]), 0x1400},
  { (subindex*)TestSlave_Index1401,sizeof(TestSlave_Index1401)/sizeof(TestSlave_Index1401[0]), 0x1401},
  { (subindex*)TestSlave_Index1402,sizeof(TestSlave_Index1402)/sizeof(TestSlave_Index1402[0]), 0x1402},
  { (subindex*)TestSlave_Index1403,sizeof(TestSlave_Index1403)/sizeof(TestSlave_Index1403[0]), 0x1403},
  { (subindex*)TestSlave_Index1600,sizeof(TestSlave_Index1600)/sizeof(TestSlave_Index1600[0]), 0x1600},
  { (subindex*)TestSlave_Index1601,sizeof(TestSlave_Index1601)/sizeof(TestSlave_Index1601[0]), 0x1601},
  { (subindex*)TestSlave_Index1602,sizeof(TestSlave_Index1602)/sizeof(TestSlave_Index1602[0]), 0x1602},
  { (subindex*)TestSlave_Index1603,sizeof(TestSlave_Index1603)/sizeof(TestSlave_Index1603[0]), 0x1603},
  { (subindex*)TestSlave_Index1800,sizeof(TestSlave_Index1800)/sizeof(TestSlave_Index1800[0]), 0x1800},
  { (subindex*)TestSlave_Index1801,sizeof(TestSlave_Index1801)/sizeof(TestSlave_Index1801[0]), 0x1801},
  { (subindex*)TestSlave_Index1802,sizeof(TestSlave_Index1802)/sizeof(TestSlave_Index1802[0]), 0x1802},
  { (subindex*)TestSlave_Index1803,sizeof(TestSlave_Index1803)/sizeof(TestSlave_Index1803[0]), 0x1803},
  { (subindex*)TestSlave_Index1A00,sizeof(TestSlave_Index1A00)/sizeof(TestSlave_Index1A00[0]), 0x1A00},
  { (subindex*)TestSlave_Index1A01,sizeof(TestSlave_Index1A01)/sizeof(TestSlave_Index1A01[0]), 0x1A01},
  { (subindex*)TestSlave_Index1A02,sizeof(TestSlave_Index1A02)/sizeof(TestSlave_Index1A02[0]), 0x1A02},
  { (subindex*)TestSlave_Index1A03,sizeof(TestSlave_Index1A03)/sizeof(TestSlave_Index1A03[0]), 0x1A03},
  { (subindex*)TestSlave_Index6000,sizeof(TestSlave_Index6000)/sizeof(TestSlave_Index6000[0]), 0x6000},
  { (subindex*)TestSlave_Index6200,sizeof(TestSlave_Index6200)/sizeof(TestSlave_Index6200[0]), 0x6200},
  { (subindex*)TestSlave_Index6040,sizeof(TestSlave_Index6040)/sizeof(TestSlave_Index6040[0]), 0x6040},
  { (subindex*)TestSlave_Index6041,sizeof(TestSlave_Index6041)/sizeof(TestSlave_Index6041[0]), 0x6041},
  { (subindex*)TestSlave_Index605A,sizeof(TestSlave_Index605A)/sizeof(TestSlave_Index605A[0]), 0x605A},
  { (subindex*)TestSlave_Index605B,sizeof(TestSlave_Index605B)/sizeof(TestSlave_Index605B[0]), 0x605B},
  { (subindex*)TestSlave_Index605C,sizeof(TestSlave_Index605C)/sizeof(TestSlave_Index605C[0]), 0x605C},
  { (subindex*)TestSlave_Index605D,sizeof(TestSlave_Index605D)/sizeof(TestSlave_Index605D[0]), 0x605D},
  { (subindex*)TestSlave_Index605E,sizeof(TestSlave_Index605E)/sizeof(TestSlave_Index605E[0]), 0x605E},
  { (subindex*)TestSlave_Index6060,sizeof(TestSlave_Index6060)/sizeof(TestSlave_Index6060[0]), 0x6060},
  { (subindex*)TestSlave_Index6061,sizeof(TestSlave_Index6061)/sizeof(TestSlave_Index6061[0]), 0x6061},
  { (subindex*)TestSlave_Index6062,sizeof(TestSlave_Index6062)/sizeof(TestSlave_Index6062[0]), 0x6062},
  { (subindex*)TestSlave_Index6064,sizeof(TestSlave_Index6064)/sizeof(TestSlave_Index6064[0]), 0x6064},
  { (subindex*)TestSlave_Index6065,sizeof(TestSlave_Index6065)/sizeof(TestSlave_Index6065[0]), 0x6065},
  { (subindex*)TestSlave_Index6066,sizeof(TestSlave_Index6066)/sizeof(TestSlave_Index6066[0]), 0x6066},
  { (subindex*)TestSlave_Index606C,sizeof(TestSlave_Index606C)/sizeof(TestSlave_Index606C[0]), 0x606C},
  { (subindex*)TestSlave_Index6071,sizeof(TestSlave_Index6071)/sizeof(TestSlave_Index6071[0]), 0x6071},
  { (subindex*)TestSlave_Index6077,sizeof(TestSlave_Index6077)/sizeof(TestSlave_Index6077[0]), 0x6077},
  { (subindex*)TestSlave_Index6087,sizeof(TestSlave_Index6087)/sizeof(TestSlave_Index6087[0]), 0x6087},
  { (subindex*)TestSlave_Index607A,sizeof(TestSlave_Index607A)/sizeof(TestSlave_Index607A[0]), 0x607A},
  { (subindex*)TestSlave_Index607D,sizeof(TestSlave_Index607D)/sizeof(TestSlave_Index607D[0]), 0x607D},
  { (subindex*)TestSlave_Index607E,sizeof(TestSlave_Index607E)/sizeof(TestSlave_Index607E[0]), 0x607E},
  { (subindex*)TestSlave_Index6080,sizeof(TestSlave_Index6080)/sizeof(TestSlave_Index6080[0]), 0x6080},
  { (subindex*)TestSlave_Index6081,sizeof(TestSlave_Index6081)/sizeof(TestSlave_Index6081[0]), 0x6081},
  { (subindex*)TestSlave_Index6083,sizeof(TestSlave_Index6083)/sizeof(TestSlave_Index6083[0]), 0x6083},
  { (subindex*)TestSlave_Index6084,sizeof(TestSlave_Index6084)/sizeof(TestSlave_Index6084[0]), 0x6084},
  { (subindex*)TestSlave_Index6098,sizeof(TestSlave_Index6098)/sizeof(TestSlave_Index6098[0]), 0x6098},
  { (subindex*)TestSlave_Index6099,sizeof(TestSlave_Index6099)/sizeof(TestSlave_Index6099[0]), 0x6099},
  { (subindex*)TestSlave_Index609A,sizeof(TestSlave_Index609A)/sizeof(TestSlave_Index609A[0]), 0x609A},
  { (subindex*)TestSlave_Index60C0,sizeof(TestSlave_Index60C0)/sizeof(TestSlave_Index60C0[0]), 0x60C0},
  { (subindex*)TestSlave_Index60C1,sizeof(TestSlave_Index60C1)/sizeof(TestSlave_Index60C1[0]), 0x60C1},
  { (subindex*)TestSlave_Index60FF,sizeof(TestSlave_Index60FF)/sizeof(TestSlave_Index60FF[0]), 0x60FF},
  { (subindex*)TestSlave_Index6085,sizeof(TestSlave_Index6085)/sizeof(TestSlave_Index6085[0]), 0x6085},
  { (subindex*)TestSlave_Index6073,sizeof(TestSlave_Index6073)/sizeof(TestSlave_Index6073[0]), 0x6073},
  { (subindex*)TestSlave_Index6072,sizeof(TestSlave_Index6072)/sizeof(TestSlave_Index6072[0]), 0x6072},
  { (subindex*)TestSlave_Index60E0,sizeof(TestSlave_Index60E0)/sizeof(TestSlave_Index60E0[0]), 0x60E0},
  { (subindex*)TestSlave_Index60E1,sizeof(TestSlave_Index60E1)/sizeof(TestSlave_Index60E1[0]), 0x60E1},
  { (subindex*)TestSlave_Index6074,sizeof(TestSlave_Index6074)/sizeof(TestSlave_Index6074[0]), 0x6074},
  { (subindex*)TestSlave_Index607F,sizeof(TestSlave_Index607F)/sizeof(TestSlave_Index607F[0]), 0x607F},
  { (subindex*)TestSlave_Index606B,sizeof(TestSlave_Index606B)/sizeof(TestSlave_Index606B[0]), 0x606B},
};

const indextable * TestSlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;  break;
		case 0x1001: i = 1;  break;
		case 0x1017: i = 2;  *callbacks = TestSlave_Index1017_callbacks; break;
		case 0x1018: i = 3;  break;
		case 0x1200: i = 4;  break;
		case 0x1400: i = 5;  break;
		case 0x1401: i = 6;  break;
		case 0x1402: i = 7;  break;
		case 0x1403: i = 8;  break;
		case 0x1600: i = 9;  break;
		case 0x1601: i = 10; break;
		case 0x1602: i = 11; break;
		case 0x1603: i = 12; break;
		case 0x1800: i = 13; *callbacks = TestSlave_Index1800_callbacks; break;
		case 0x1801: i = 14; *callbacks = TestSlave_Index1801_callbacks; break;
		case 0x1802: i = 15; *callbacks = TestSlave_Index1802_callbacks; break;
		case 0x1803: i = 16; *callbacks = TestSlave_Index1803_callbacks; break;
		case 0x1A00: i = 17; break;
		case 0x1A01: i = 18; break;
		case 0x1A02: i = 19; break;
		case 0x1A03: i = 20; break;
    case 0x6000: i = 21; break;
    case 0x6200: i = 22; break;
    case 0x6040: i = 23; *callbacks = TestSlave_Index6040_callbacks; break; // ControlWord
    case 0x6041: i = 24; break;
    case 0x605A: i = 25; break;
    case 0x605B: i = 26; break;
    case 0x605C: i = 27; break;
    case 0x605D: i = 28; break;
    case 0x605E: i = 29; break;
    case 0x6060: i = 30; *callbacks = TestSlave_Index6060_callbacks; break; // Modes of operation
    case 0x6061: i = 31; break;
    case 0x6062: i = 32; break;
    case 0x6064: i = 33; break;
    case 0x6065: i = 34; break;
    case 0x6066: i = 35; break;
    case 0x606C: i = 36; break;
    case 0x6071: i = 37; *callbacks = TestSlave_Index6071_callbacks; break; // Target Torque
    case 0x6077: i = 38; break;
    case 0x6087: i = 39; break;
    case 0x607A: i = 40; *callbacks = TestSlave_Index607A_callbacks; break; // Target Position
    case 0x607D: i = 41; break;
    case 0x607E: i = 42; break;
    case 0x6080: i = 43; break;
    case 0x6081: i = 44; *callbacks = TestSlave_Index6081_callbacks; break; // Profile Velocity
    case 0x6083: i = 45; break;
    case 0x6084: i = 46; break;
    case 0x6098: i = 47; *callbacks = TestSlave_Index6098_callbacks; break; // Homing Method
    case 0x6099: i = 48; break;
    case 0x609A: i = 49; break;
    case 0x60C0: i = 50; break;
    case 0x60C1: i = 51; break;
    case 0x60FF: i = 52; *callbacks = TestSlave_Index60FF_callbacks; break; // Target Velocity
    case 0x6085: i = 53; break;
    case 0x6073: i = 54; break;
    case 0x6072: i = 55; break;
    case 0x60E0: i = 56; break;
    case 0x60E1: i = 57; break;
    case 0x6074: i = 58; break;
    case 0x607F: i = 59; break;
    case 0x606B: i = 60; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TestSlave_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TestSlave_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index TestSlave_firstIndex = {
  4, /* SDO_SVR */
  0, /* SDO_CLT */
  5, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  13, /* PDO_TRS */
  17 /* PDO_TRS_MAP */
};

const quick_index TestSlave_lastIndex = {
  4, /* SDO_SVR */
  0, /* SDO_CLT */
  8, /* PDO_RCV */
  12, /* PDO_RCV_MAP */
  16, /* PDO_TRS */
  20 /* PDO_TRS_MAP */
};

const UNS16 TestSlave_ObjdictSize = sizeof(TestSlave_objdict)/sizeof(TestSlave_objdict[0]); 

CO_Data TestSlave_Data = CANOPEN_NODE_DATA_INITIALIZER(TestSlave);

